---
name: akonadi
base: core22
adopt-info: akregator
confinement: strict
grade: stable
assumes:
- snapd2.55.3
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  # - build-on: armhf
  # - build-on: ppc64el

slots:
    dbus-svc:
        interface: dbus
        bus: system
        name: org.freedesktop.Akonadi
apps:
    akonadiserver:
        command: usr/bin/akonadiserver
        daemon: simple
        slots: [dbus-svc]

package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-108-qt-5-15-10-core22
        build-snaps:
        - kf5-5-108-qt-5-15-10-core22-sdk
        build-environment:
        - &id001
            PATH: /snap/kf5-5-108-qt-5-15-10-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf5-5-108-qt-5-15-10-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kf5-5-108-qt-5-15-10-core22-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
        - &id004
            CRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-108-qt-5-15-10-core22-sdk/current${CRAFT_CMAKE_ARGS:+:$CRAFT_CMAKE_ARGS}
    akonadi:
        after:
        - kde-neon
        parse-info:
        - usr/share/metainfo/org.kde.akregator.appdata.xml
        plugin: cmake
        build-packages:
        - cmake
        - libaccounts-qt5-dev
        - libkaccounts-dev
        - xsltproc
        - lzma-dev
        stage-packages:
        - libaccounts-qt5-1
        - libkaccounts2
        source: https://invent.kde.org/pim/akonadi.git
        source-tag: v23.08.0
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-108-qt-5-15-10-core22-sdk/current"
        build-environment: &id005
        - *id001
        - *id002
        - *id003
        - *id004
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    cleanup:
        after:
        - akonadi
        plugin: nil
        override-prime: |
            set -eux
            #unused libs from linters
